import styled from '@emotion/styled';
import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import useDialog from '../dialogs/store';

const Home: NextPage = () => {
  const [showAlertDialog, showConfirmDialog] = useDialog((state) => [
    state.showAlertDialog,
    state.showConfirmDialog,
  ]);
  return (
    <div
      style={{
        height: 'calc(100vh - 48px)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <Head>
        <title>모바일 청접장</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>메인 페이지</h1>
      </div>
    </div>
  );
};

export default Home;
