import styled from '@emotion/styled';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Header from '../components/Header';
import useDialog from '../dialogs/store';

const UnderlinedLink = styled.a`
  text-decoration: underline;
  color: grey;
  &:hover {
    color: black;
  }
`;

const Home: NextPage = () => {
  const [showAlertDialog, showConfirmDialog] = useDialog((state) => [
    state.showAlertDialog,
    state.showConfirmDialog,
  ]);

  return (
    <div
      style={{
        height: 'calc(100vh - 48px)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <Head>
        <title>모바일 청접장</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <h1>메인 페이지</h1>
        <Link href={'/invitation?id=cssEq05cBqawFl8VqMAg'}>
          <UnderlinedLink>예시 보러가기</UnderlinedLink>
        </Link>
      </div>
    </div>
  );
};

export default Home;
